name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        cache: sbt
    - name: Cache Data
      uses: actions/cache@v1
      env:
        ndk: android-ndk-r12b
        sdk-tools: 4333796
        scala-version: scala-2.11.8
      with:
        path: ~/.android-cache
        key: ${{ runner.os }}-android-${{ env.ndk-version }}-${{ env.sdk-tools }}-${{ env.scala-version }}
        restore-keys: |
          ${{ runner.os }}-android-${{ env.ndk-version }}-${{ env.sdk-tools }}        
    - name: Setup Scala
      run: |
        # sudo apt-get remove scala-library scala
        mkdir -p ~/.android-cache
        sudo /bin/sh -c 'if [ ! -f ~/.android-cache/scala-2.11.8.deb ]; then sudo wget -O ~/.android-cache/scala-2.11.8.deb www.scala-lang.org/files/archive/scala-2.11.8.deb; fi'
        sudo dpkg -i ~/.android-cache/scala-2.11.8.deb
    - name: init Application.mk
      run: |
        echo -e "APP_ABI      			:= armeabi-v7a x86\nAPP_PLATFORM 			:= android-16\nAPP_STL      			:= stlport_static\nNDK_TOOLCHAIN_VERSION 	:= clang\n" > './src/main/jni/Application.mk'
    - name: Build apk
      run: |
        ./travis-ci/setup.sh
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: aikor-vpn-build-release
        path: target/android/output/aikor-vpn-release.apk
    - name: Check Build
      run: |
        ls -thls ~/.android-cache
        ls -thla ./target/android/output/
        echo test, and deploy your project.